- hosts: all
  gather_facts: yes
  become: yes
  vars_prompt:
    - name: "node_ip"
      prompt: "Enter your public IP"
      private: no
    - name: "password"
      prompt: "Enter your keystore password"
      private: yes
    - name: "node_email"
      prompt: "Enter your email"
      private: no
    - name: "node_name"
      prompt: "Enter your node name"
      private: no
  roles:
    - lacchain-validator-node
