---
- name: backup
  debug:
      msg: "Backing up current node keys"

- name: get public ip
  shell: dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null || curl -s --retry 2 icanhazip.com
  register: node_ip

- name: create backup directories
  file:
      path: "{{ item.dest }}"
      mode: "{{ item.mode }}"
      state: directory
  with_items:
      - { dest: "~/lacchain-keysBackup", mode: "0440" }
      - { dest: "~/lacchain-keysBackup/data", mode: "0440" }
      - { dest: "~/lacchain-keysBackup/data/geth", mode: "0440" }
      - { dest: "~/lacchain-keysBackup/data/constellation", mode: "0440" }
      - { dest: "~/lacchain-keysBackup/data/keystore", mode: "0440" }

- name: Copy constellation keys
  copy:
      src: ~/lacchain/data/constellation/keystore
      dest: ~/lacchain-keysBackup/data/constellation
      remote_src: yes
  when: not validator

- name: Copy node keys
  copy:
      src: "~/lacchain/data/keystore/{{ item }}"
      dest: ~/lacchain-keysBackup/data/keystore
      remote_src: yes
  with_fileglob:
      - UTC*

- name: Copy enode ID
  copy:
      src: ~/lacchain/data/geth/nodekey
      dest: ~/lacchain-keysBackup/data/geth/nodekey
      remote_src: yes

- name: save enode in variable
  shell: bootnode -nodekey ~/lacchain-keysBackup/data/geth/nodekey -writeaddress
  register: enode_key

- name: print enode key
  debug:
      msg: enode://{{enode_key.stdout}}@{{node_ip.stdout}}:21000?discport=0
