---
- name: update node
  debug:
    msg: "Update Node"

- name: Copy permissioned nodes file
  copy:
    src: "{{ playbook_dir }}/roles/lacchain-validator-node/files/permissioned-nodes_validator.json"
    dest: ~/lacchain/data/permissioned-nodes.json
    mode: 0755
  when: validator == 'yes'

- name: copy static nodes to node validator
  copy:
    src: "{{ playbook_dir }}/roles/lacchain-validator-node/files/permissioned-nodes_validator.json"
    dest: ~/lacchain/data/static-nodes.json
    mode: 0755
  when: validator == 'yes'

- name: Copy general nodes file
  copy:
    src: "{{ playbook_dir }}/roles/lacchain-regular-node/files/permissioned-nodes_general.json"
    dest: ~/lacchain/data/permissioned-nodes.json
    mode: 0755
  when: regular == 'yes'
