---
- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "ubuntu-dependencies.yml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "rhel-dependencies.yml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')

- name: install java
  import_tasks: "install-java.yaml"

- name: install pantheon
  import_tasks: "install-pantheon.yaml"

- name: init pantheon
  import_tasks: "init-pantheon.yaml"

- name: start node
  import_tasks: "start-node.yaml"
  when: first_node

- name: clean files
  import_tasks: "clean-files.yaml"
